MLOPS-346 Separate Ambassador module from Seldon module
datarevenue-berlin/OpenMLOps pull request #50
Opened 2021-07-13 21:05 UTC by bernardolk

2021-07-14 14:15 UTC, bernardolk commented
Needs to be tested and a review

2021-07-16 14:28 UTC, tvinagre requested changes
Awesome! Thanks @bernardolk just some small suggestions. Let's just test is on the cluster before merging :)

2021-07-16 14:28 UTC, tvinagre commented on main.tf
> +  source    = "./modules/ambassador"
Would be good to add `namespace` here as well

2021-07-16 14:28 UTC, tvinagre commented on modules/ambassador/main.tf
> +  namespace = var.ambassador_namespace
could you rename this var to `namespace` please? So it gets consistent with the rest of the repo

2021-07-16 14:28 UTC, tvinagre commented on modules/ambassador/main.tf
> +
Also, I'm missing a HELM version here, would be good to add to prevent future issues

2021-07-16 14:28 UTC, tvinagre commented on main.tf
> +resource "kubernetes_namespace" "ambassador_namespace" {
You fixed the typo, nice :)

2021-07-16 14:28 UTC, tvinagre commented on modules/seldon/variables.tf
> +variable "seldon_namespace" {
Please let's just keep `namespace`. Also, if you rename it here, you need to change on `main.tf`, where the `module` gets called

2021-07-16 14:44 UTC, bernardolk commented on main.tf
> +resource "kubernetes_namespace" "ambassador_namespace" {
🦾

2021-07-21 22:14 UTC, merged